# Nexus5XPkg CI build on VSTS

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - LICENSE

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo apt update 
  displayName: 'Update APT sources'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    architecture: 'x64'
  displayName: Install correct Python

- script: sudo apt install -y uuid-dev clang llvm gcc-aarch64-linux-gnu
  displayName: 'Install VSTS dependencies'

- script: |
    git submodule update --init --recursive
  displayName: Fetch Submodules

# Initialize submodules
- script: git submodule init
  displayName: 'Initialize submodules'

- script: sudo apt install -y mkbootimg
  displayName: 'Install mkbootimg'

- script: export CLANG38_BIN=/usr/lib/llvm-38/bin/ && export CLANG38_AARCH64_PREFIX=aarch64-linux-gnu-
  displayName: 'Setup CLANG environment'

- script: pip install --upgrade -r ./pip-requirements.txt
  displayName: 'Install Python dependencies'

- script: chmod +x ./build_releaseinfo.ps1 && ./build_releaseinfo.ps1
  displayName: 'Stamp build'

- script: chmod +x ./build_uefi_bullhead.sh && ./build_uefi_bullhead.sh
  displayName: 'UEFI build (Nexus 5X)'

- script: chmod +x ./build_uefi_angler.sh && ./build_uefi_angler.sh
  displayName: 'UEFI build (Nexus 6P)'

- script: chmod +x ./build_boot_shim.sh && ./build_boot_shim.sh
  displayName: 'BootShim build'

- script: chmod +x ./build_boot_images.sh && ./build_boot_images.sh
  displayName: 'UEFI boot image build'

# Publish UEFI (2 targets)
- task: PublishBuildArtifacts@1
  displayName: 'Publish MSM8992 UEFI build (Nexus 5X)'
  inputs:
    pathtoPublish: ./ImageResources/Bullhead/uefi.img
    artifactName: MSM8992 UEFI (Nexus 5X)

- task: PublishBuildArtifacts@1
  displayName: 'Publish MSM8994 UEFI build (Nexus 6P)'
  inputs:
    pathtoPublish: ./ImageResources/Angler/uefi.img
    artifactName: MSM8994 UEFI (Nexus 6P)